version: '3.9'
name: banking-service
services:
  sql-server:
    container_name: banking-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
       - ./docker/sql/mssql:/var/opt/mssql
